# Generated by Django 4.2.4 on 2023-11-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('url_img', models.URLField()),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('shared', models.IntegerField(blank=True, null=True)),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paisajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador1', models.IntegerField(default=0)),
                ('contador2', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
