# Generated by Django 4.2.4 on 2023-11-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('url_img', models.CharField(max_length=300)),
                ('likes', models.IntegerField()),
                ('shared', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Paisajes',
            new_name='Paisaje2',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
