# Generated by Django 4.2.5 on 2023-11-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='laikeros',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
