# Generated by Django 4.2.5 on 2023-11-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_noticias_laikeros_alter_noticias_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='laikeros',
            field=models.JSONField(default=list),
        ),
    ]
