# Generated by Django 4.2.4 on 2023-11-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_noticia2_rename_paisajes_paisaje2_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('url_img', models.URLField()),
                ('likes', models.IntegerField()),
                ('shared', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Noticia2',
        ),
    ]
