# Generated by Django 4.2.4 on 2023-11-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_noticias_delete_noticia2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='shared',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
