# Generated by Django 4.2.5 on 2023-11-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_alter_noticias_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
